sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_script:
    - pip install Django
    - pip install pep8
script:
    - pep8 commonconf
    - DJANGO_SETTINGS_MODULE=travis_ci.settings python tests.py

